name: Test Install

on: [push]

jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -f .verify/Dockerfile -t dotfiles-test .

      - name: Run Verification
        run: docker run -t dotfiles-test bash -c "yes | /tmp/install.sh && /tmp/verify.sh" 

